//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NFWebServer
{
    
    internal partial class Resource
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((Resource.manager == null))
                {
                    Resource.manager = new System.Resources.ResourceManager("NFWebServer.Resource", typeof(Resource).Assembly);
                }
                return Resource.manager;
            }
        }
        internal static string GetString(Resource.StringResources id)
        {
            return ((string)(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        internal static byte[] GetBytes(Resource.BinaryResources id)
        {
            return ((byte[])(nanoFramework.Runtime.Native.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum BinaryResources : short
        {
            Slide8 = -29178,
            favicon = -22914,
            Slide2 = -15986,
            Slide9 = -15245,
            Slide11 = 516,
            Slide10 = 517,
            Slide13 = 518,
            Slide12 = 519,
            Slide15 = 520,
            Slide14 = 521,
            Slide17 = 522,
            Slide16 = 523,
            Slide18 = 541,
            Slide5 = 1149,
            Slide4 = 11824,
            Slide3 = 12530,
            Slide1 = 21623,
            Slide7 = 23036,
            Slide6 = 31416,
        }
        [System.SerializableAttribute()]
        internal enum StringResources : short
        {
            slide6html = -24011,
            slide7html = -20935,
            slide5html = -19739,
            slide4html = -18015,
            slide11html = -16309,
            slide10html = -13228,
            slide16html = -9398,
            slide2html = -8586,
            slide17html = -8375,
            slide18html = -7604,
            slide12html = -5290,
            slide13html = -4267,
            slide8html = 4671,
            slide9html = 8143,
            slide3html = 11220,
            slide15html = 12360,
            slide1html = 13600,
            slide14html = 15439,
        }
    }
}
